name:                coffee-order
version:             0.1.0.0
homepage:            https://github.com/google/proto-tutorial/coffee-order#readme
license:             BSD3
author:              Fintan Halpenny
maintainer:          fintan.halpenny@gmail.com
copyright:           2017 Google Inc.
category:            Data
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - coffee-proto
  - data-default
  - microlens
  - proto-lens
  - lens-labels
  - text

executables:
  gimme-coffee:
    source-dirs:      src
    main:             Main.hs
